
int tmin();
int test_tmin();
int bitOr(int, int);
int test_bitOr(int, int);
int negate(int);
int test_negate(int);
int isEqual(int, int);
int test_isEqual(int, int);
int absVal(int);
int test_absVal(int);
int isLess(int, int);
int test_isLess(int, int);
int satAdd(int, int);
int test_satAdd(int, int);
int dividePower2(int, int);
int test_dividePower2(int, int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
unsigned floatNegate(unsigned);
unsigned test_floatNegate(unsigned);
int floatIsEqual(unsigned, unsigned);
int test_floatIsEqual(unsigned, unsigned);
int floatFloat2Int(unsigned);
int test_floatFloat2Int(unsigned);
